### ISSUE TITLE
How to construct a direct visibility graph

### ISSUE THREAD

**Issue by SunderlandAJ-1130** [CarlosBergillos/ts2vg#1]
Hi!

I want to apply this method to construct a direct visibility graph. How can I do this?

Thanks!

**Comment by CarlosBergillos** [comment]
Hi!

You mean a graph with the edges having direction consistent with the temporal axis? Or something else?

In any case, only undirected and unweighted graphs are supported currently, but I would like to add more versions.

**Comment by CarlosBergillos** [comment]
Starting with v1.0.0, ts2vg now implements directed graphs.

See: [basic usage](https://carlosbergillos.github.io/ts2vg/index.html#directed-visibility-graph) and [examples](https://carlosbergillos.github.io/ts2vg/examples.html#directed-graphs).

I'm closing the issue now. (commit 953a6c8)
