### ISSUE TITLE
Horizontal Visibility Graph

### ISSUE THREAD

**Issue by taulokoka** [CarlosBergillos/ts2vg#2]
Hi,

is there a possibility to add the horizontal visibility graph as well?

**Comment by CarlosBergillos** [comment]
Hi!
I'm actually working on adding Horizontal Visibility Graphs (and other variations) already.

It's not ready for publishing yet, but hopefully in the next weeks.

If you need it urgently let me know and I can provide you with a working but not documented version earlier :D.

**Comment by taulokoka** [comment]
Thanks for the reply! Great to know you are already working on it.

It's not urgent at the moment, so no need to rush! :)

**Comment by taulokoka** [comment]
Hi I am reopening, because I want to ask if you could provide the uncommented version of the horizontal visibility graph :)

Thanks in advance!

**Comment by CarlosBergillos** [comment]
Hi, thanks for the interest, and sorry for the delays.

You'll have it this next week :)

**Comment by taulokoka** [comment]
Don't worry about it, thanks for the efoort! :)

**Comment by CarlosBergillos** [comment]
Hi! I just released an update to the library that now includes Horizontal Visibility graphs :) (ts2vg v1.0.0)

See: [basic usage](https://carlosbergillos.github.io/ts2vg/index.html#horizontal-visibility-graph), [examples](https://carlosbergillos.github.io/ts2vg/examples.html#horizontal-visibility-graphs), and [documentation](https://carlosbergillos.github.io/ts2vg/api/horizontalvg.html).

I'm closing the issue now. (commit 953a6c8)

If you experience any problems please report :)
