### ISSUE TITLE
Error while installing ts2vg due to Wheel 

### ISSUE THREAD

**Issue by nhaboudal** [CarlosBergillos/ts2vg#22]
hello I get this error when trying to install ts2vg 

Installing ts2vg...
Resolving ts2vg...
Installing...
⠧ Installing ts2vg...[31m[1mError: [0m An error occurred while installing [32mts2vg[0m!
Error text: Collecting ts2vg
  Using cached ts2vg-1.2.1.tar.gz (643 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

[36m  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File 
"/opt/homebrew/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process
.py", line 353, in <module>
          main()
        File 
"/opt/homebrew/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process
.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File 
"/opt/homebrew/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process
.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 49, in <module>
        File "<string>", line 43, in main
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % 
filepattern):
        File 
"/private/var/folders/4c/zgw8q2mx7plgt4ndx3mdg5zw0000gn/T/pip-build-env-bag7tkml/overlay/lib/python3.11/site-p
ackages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ts2vg/utils/pairqueue.pyx' doesn't match any files
      
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[0m
✘ Installation Failed

**Comment by CarlosBergillos** [comment]
Hi! Are you running on macOS? If so, which version of macOS?

**Comment by nhaboudal** [comment]
Hi ! yes , macOs Monterey version 12.5 (21G72)

**Comment by CarlosBergillos** [comment]
Cool thanks, that's useful to know. And what version of pip are you using? (you can run `pip --version` to check)

**Comment by nhaboudal** [comment]
version : pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)

**Comment by CarlosBergillos** [comment]
I've built and published some new macOS wheels.

Can you try and execute `pip install ts2vg` again and see if that fixes it?

**Comment by nhaboudal** [comment]
Hi Carlos, 
Thank you so much !
works perfectly.

**Comment by CarlosBergillos** [comment]
Awesome! :D
