### ISSUE TITLE
Disaster

### ISSUE THREAD

**Issue by JTJest** [CarlosBergillos/ts2vg#25]
After 4 months of solid operation, the sample example completely fell apart. The time series is displayed ok. Everything else is also in ruins. Not only are there no axis descriptions, but there are absolutely no usable graphs. I am greatly disappointed. Josef

**Comment by CarlosBergillos** [comment]
I am sorry to hear that. However I am unable to help you if you don't provide more information.

Did you recently update Python, ts2vg, or any of the other Python packages used?
And are your problems related only to the visual plots? (and the ts2vg computations work fine) if so, the problems might be with your Matplotlib installation and not with ts2vg.

**Comment by JTJest** [comment]
Thank you very much for the immediate response.

Yes, I reinstalled Numpy. Matplotlib I don't remember doing anything with it.  

There are versions:

NetworkX version: 2.5
Matplotlib version: 3.7.1
Numpy: 2.5

And I am attaching the graphic outputs.

Thx for help.

Josef

**Comment by CarlosBergillos** [comment]
I don't see the images, can you upload them in the web and not via email?

And what version of ts2vg are you using?

And can you re-check the Numpt version? The one you said doesn't seem to exist.

Thanks!

**Comment by JTJest** [comment]
Thanks for the reply ... but we could continue tomorrow. I'm here around midnight. Thanks for understanding. Josef

**Comment by JTJest** [comment]
Hello again from Prague, 

I was probably quite depressed yesterday (sorry about that) because next week I have a presentation of my work (networks, HVG...)
I managed to find out the version of Numpy: 1.21.3
However, it failed to detect the version of ts2vg in the usual way.

from ts2vg import NaturalVG
print (ts2vg.__version__)


I'm sending the pictures again (I didn't know how to use the WEB, so I sent them again by email), hopefully they will be readable.

Have nice day and thanks for the answer. J. Toman

**Comment by CarlosBergillos** [comment]
Hi Josef, no problem.

To find the ts2vg version run this:

```python
import ts2vg
print(ts2vg.__version__)
```

And I still don't see the images unfortunately.
Reply in the web here: https://github.com/CarlosBergillos/ts2vg/issues/25
and just drag & drop the file in the text box to attatch it.

In any case, maybe it's a good idea to uninstall ts2vg & Matplotlib and install them again, or look into using a virtual environment for Python.

**Comment by JTJest** [comment]
Hi Carlos,

I tried import ts2vg
print(ts2vg.__version__)
… but doesn’t work. 

In the end, the matter was resolved by massively downgrading the versions of Anacona, Python, Numpy.
Have a nice day. Josef
 

> 26. 5. 2023 v 21:59, Carlos Bergillos ***@***.***>:
> 
> import ts2vg
> print(ts2vg.__version__)
