### ISSUE TITLE
Plot visibility graph using ts2vg

### ISSUE THREAD

**Issue by zoubaihan** [CarlosBergillos/ts2vg#33]
Hi, I want show the specific graph structure in a figure.  Can ts2vg plot visibility graph? How to plot a figure just like this:
![image](https://github.com/CarlosBergillos/ts2vg/assets/60840371/c2e59737-54fd-4ac8-a68e-64ae0a27727c)
Do you have a plan to add this function?

**Comment by CarlosBergillos** [comment]
Hi, I don't plan to include plotting as part of ts2vg, but you can make these kind of visualizations with the [Matplotlib library](https://matplotlib.org/), or other similar libraries. The above image was made with Matplotlib.

For simple examples and their code check out the examples here:
https://carlosbergillos.github.io/ts2vg/examples.html
