### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by Yuheng0912** [CarlosBergillos/ts2vg#34]
The example in the library is to input a piece of series data, how do I add time series data? Are there any time limits?

**Comment by CarlosBergillos** [comment]
Hello!

I'm not sure I'm understanding this.
But I'll try to give some info.

The series given as input to ts2vg is by default assumed to be an equally spaced time series with the time dimension (x coordinates) of the points being one unit spaced (at 0, 1, 2, ...).

Note though, that the exact scale of the spacing along the time dimension is irrelevant in the construction of visibility graphs and does not affect the output (unless in the calculation of edge weights).

If you have a time series with non-equal spacings, or, if the scale of the spacings is relevant for the calculation of edge weights, you can explicitly provide the time dimension (x coordinates) of the time series via the `xs` argument to the [`build` method](https://carlosbergillos.github.io/ts2vg/api/ts2vg.NaturalVG.html#ts2vg.NaturalVG.build). For example:

```
NaturalVG().build([2,4,2], xs=[1, 2.5, 10])
```

I hope this helps!

**Comment by Yuheng0912** [comment]
Thank you very much for your answer, I want to build a visibility graph with unequal time series spacing (which will involve weights), so how should the first time point in the xs parameter you use be valued, the first one is 0 or 1?

**Comment by CarlosBergillos** [comment]
The two series given to ts2vg (`ts` and `xs`) should have the same length.
The first element in `xs` is the x coordinate for the first element in `ts`, the second element in `xs` is the x coordinate for the first element in `ts`, and so on.

For example:
```
NaturalVG().build(ts=[2,4,2], xs=[1, 2.5, 10])
```
builds the visibility graph for the time series with the following `(x, y)` points:
```
(1, 2), (2.5, 4), (10, 2)
```

**Comment by Yuheng0912** [comment]
Thanks for the answer! Here I already understand. Now I wonder if there is a strict requirement for two adjacent time intervals here?

**Comment by CarlosBergillos** [comment]
Good to hear!

I don't understand what you mean by "two adjacent time intervals" though.

**Comment by CarlosBergillos** [comment]
The only requirement is that the x coordinate (time component) needs to be increasing, but there is not requirement for the spacing between observations to be constant, if that is what you are asking.

**Comment by CarlosBergillos** [comment]
Afaik there is no issue here.
